**Day 1: Basics of Pytorch**

**Introduction to Tensors in PyTorch**

What Are Tensors?
Tensors are the fundamental building blocks of PyTorch. They are multi-dimensional arrays similar to NumPy arrays but with additional capabilities, such as running on GPUs for faster computation.

A tensor can represent:

Scalar (0D Tensor) → A single number (e.g., 3.14)

Vector (1D Tensor) → A 1D array (e.g., [1, 2, 3])

Matrix (2D Tensor) → A 2D array (e.g., [[1, 2], [3, 4]])

Higher-Dimensional Tensors (3D, 4D, etc.) → Used for deep learning, images, videos, etc.

Why Use Tensors Instead of NumPy?

**GPU Support** – PyTorch tensors can run on GPUs, making them much faster than NumPy for large computations.

**Automatic Differentiation** – PyTorch tensors work with autograd, which is essential for deep learning.

**Deep Learning** – PyTorch models use tensors for training and inference.

Creating Tensors in PyTorch

Let's see how to create different types of tensors:

In [2]:
import torch

# Creating a simple tensor
x = torch.tensor([1,2,3])
print(x)

# Tensor filled with zeros, If you have used numpy before most of this functions might seem familiar
zeros = torch.zeros(3,3)
print(zeros)

# Tensor filled with ones
ones = torch.ones(2,2)
print(ones)

# Random tensor
rand_tensor = torch.rand(2,3)
print(rand_tensor)

# Identity matric
eye = torch.eye(3)
print(eye)

arange_tensor = torch.arange(0,10,2)
print(arange_tensor)


tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5209, 0.8132, 0.4436],
        [0.4182, 0.6369, 0.7515]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 2, 4, 6, 8])


**Checking Tensor Properties**

Every tensor has important properties:

In [3]:
x = torch.rand(3, 4)
print("Shape:", x.shape)  # Shape of tensor
print("Data type:", x.dtype)  # Data type
print("Device:", x.device)  # Where the tensor is stored (CPU/GPU)


Shape: torch.Size([3, 4])
Data type: torch.float32
Device: cpu


**Basic Tensor Operations**

You can perform various operations on tensors just like in NumPy:

In [4]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise addition
print(a + b)

# Element-wise multiplication
print(a * b)

# Matrix multiplication
A = torch.rand(2, 3)
B = torch.rand(3, 2)
C = torch.mm(A, B)  # Matrix multiplication
print(C)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([[0.4543, 0.7116],
        [0.2909, 0.4511]])


**Broadcasting in PyTorch**

Broadcasting is a technique that automatically expands the dimensions of tensors so they can be used together in arithmetic operations without explicit reshaping

This is similar to NumPy broadcasting, allowing operations on tensors of different shapes without unnecessary memory duplication.

**Example 1: Scalar with a Tensor**

A scalar (single number) automatically broadcasts across all elements of a tensor

In [5]:
x = torch.tensor([1, 2, 3])  # Shape: (3,)
y = 2  # Scalar

print(x + y)  # [3, 4, 5]

tensor([3, 4, 5])


**Example 2: Different Shapes (1D & 2D Tensor)**

In [6]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
b = torch.tensor([10, 20, 30])  # Shape: (3,)

print(a + b)


tensor([[11, 22, 33],
        [14, 25, 36]])


**Example 3: Expanding a Column Vector**



In [7]:
a = torch.tensor([[1], [2], [3]])  # Shape: (3, 1)
b = torch.tensor([10, 20, 30])  # Shape: (3,)

print(a + b)


tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])


**When Broadcasting Fails**

If PyTorch can’t match dimensions, it throws an error:


In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 4)

print(a + b) 

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

**How to Expand a Tensor Manually?**

If broadcasting fails, you can explicitly reshape a tensor using unsqueeze() or expand().


In [11]:
a = torch.tensor([1, 2, 3])  # Shape: (3,)
b = a.unsqueeze(1)  # Shape: (3,1)
print(b)
print(b.expand(3, 3))  # Expands to (3,3)


tensor([[1],
        [2],
        [3]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


**Moving Tensors to GPU**

If you have a GPU, you can move tensors to it for faster computation:

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.rand(3, 3).to(device)
print("Tensor on:", tensor.device)


Tensor on: cpu
